name: minha-empresa-teste-ltda       # ex: minha-empresa-teste-ltda
description: "Template de app para empresas"
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
  
